vdaas/web

Makefile, README.md
I added `subup` command for check submodule update before deploy each env.
And also, I added `latest` for check version and sync document before deploy.
=> check submodule update

themes/vald/layouts/_default/single.html, themes/vald/static/css/main.css
remove class from tags in <nav>
=> fix html,css

Makefile, themes/vald/archetypes/default.md, themes/vald/layouts/_default/baseof.html, themes/vald/layouts/_default/list.html, themes/vald/layouts/_default/single.html, themes/vald/layouts/partials/header.html, themes/vald/layouts/partials/sidebar.html, themes/vald/layouts/partials/toc.html, themes/vald/static/css/main.css
I implemented following:
- add `sidebar.html` and `toc.html` for single page
- fix `single.html`
- update sync document way
- update public and staging page
=> add template of sidebar and toc

Makefile, archetypes/default.md, config/_default/config.toml, config/production/config.toml, config/staging/config.toml, init.sh, themes/vald/layouts/_default/baseof.html, themes/vald/layouts/partials/header.html, themes/vald/layouts/partials/menu.html, themes/vald/layouts/partials/menu/default.html, themes/vald/layouts/partials/menu/version.html
I refactored `archetypes/default.md` for create content each version without warning when showing sidebar.
- update archetyped/default.md and template
- update sync document and images
- create `init.sh` for update document, which includes check version, download latest document, create contents and images
- fix some bugs.
=> update archetypes for document each version

themes/vald/layouts/_default/single.html, themes/vald/layouts/partials/sidebar.html, themes/vald/layouts/partials/toc.html, themes/vald/static/css/main.css, themes/vald/static/js/script.js
task board
https://github.com/vdaas/web/projects/1#card-39481653
toc
- fix toc (#current ) css to position fixed as default
- add js to open and close toc menu when viewing page on smartphone
page sidebar
-changed arrow color on darktheme
bug fix
-wrong js code worked to add `body` to take some margin. deleted this code
toc
page sidebar
=> modify js and related code

.github/workflows/auto-minify.yml, Makefile, README.md, config/_default/config.toml, themes/vald/layouts/_default/baseof.html
I updated for SEO:
- `config/_default/config.toml`
- `themes/vald/layouts/_default/baseof.html`
And maintained `Makefile` for add github actions.
=> update for SEO

.github/workflows/auto-minify.yml, .github/workflows/release-prod.yml
I refactored checkout action at github actions
=> update checkout action

.github/workflows/auto-minify.yml, .github/workflows/release-prod.yml
I fixed checkout actions which is return failed.
=> fix workflow checkou actions

.github/workflows/auto-minify.yml, .github/workflows/release-prod.yml
=> fix workflow

content/docs/contributing/coding-style.md, content/docs/contributing/contributing-guide.md, content/docs/overview/about-vald.md, content/docs/overview/architecture.md, content/docs/overview/component/index.md, content/docs/release/CHANGELOG.md, content/docs/support/contacts.md, content/docs/tutorial/agent-on-docker.md, content/docs/tutorial/get-started.md, content/docs/usecase/usage-example.md, content/docs/user-guides/configuration.md
released v0.0.46
I just released without CI because I'm not sure CI will work correct.
I'll check workflow later.
=> release 0.0.46

content/docs/contributing/coding-style.md, content/docs/contributing/contributing-guide.md, content/docs/overview/about-vald.md, content/docs/overview/architecture.md, content/docs/release/CHANGELOG.md, content/docs/support/contacts.md, content/docs/tutorial/agent-on-docker.md, content/docs/tutorial/get-started.md, content/docs/usecase/usage-example.md, content/docs/user-guides/configuration.md
=> release v0.0.50

.github/workflows/release-prod.yml
=> release 20200812

content/docs/tutorial/agent-on-docker.md, content/docs/tutorial/get-started.md
=> release jpsearch

content/docs/overview/component/index.md
=> release version v0.0.52_1

Makefile, content/docs/contributing/_index.md, content/docs/overview/_index.md, content/docs/performance/_index.md, content/docs/release/_index.md, content/docs/release/changelog.md, content/docs/support/_index.md, content/docs/tutorial/_index.md, content/docs/usecase/_index.md, content/docs/user-guides/_index.md, themes/vald/layouts/partials/menu.html, themes/vald/layouts/partials/sidebar.html
=> fix bugs and refactor template

Makefile, content/docs/contributing/coding-style.md, content/docs/contributing/contributing-guide.md, content/docs/contributing/unit-test-guideline.md, content/docs/release/_index.md, content/docs/release/changelog.md, content/docs/support/_index.md, content/docs/support/contacts.md, content/docs/tutorial/vald-agent-standalone-on-docker.md, content/docs/v1.1/contributing/_index.md, content/docs/v1.1/contributing/coding-style.md, content/docs/v1.1/contributing/contributing-guide.md, content/docs/v1.1/contributing/unit-test-guideline.md, content/docs/v1.1/release/_index.md, content/docs/v1.1/release/changelog.md, content/docs/v1.1/tutorial/_index.md, content/docs/v1.1/tutorial/get-started.md, content/docs/v1.1/tutorial/using-backup-with-scylladb.md, content/docs/v1.1/tutorial/vald-agent-standalone-on-docker.md, content/docs/v1.1/tutorial/vald-agent-standalone-on-k8s.md
=> release v1.1.1

Makefile, content/docs/contributing/coding-style.md, content/docs/release/changelog.md, content/docs/v1.1/contributing/coding-style.md, content/docs/v1.1/release/changelog.md, content/docs/v1.1/tutorial/using-backup-with-scylladb.md, content/docs/v1.1/tutorial/vald-agent-standalone-on-docker.md
=> release v1.1.2

content/docs/overview/architecture.md, content/docs/overview/data-flow.md, content/docs/release/changelog.md, content/docs/user-guides/configuration.md
=> release unpublished document

themes/vald/layouts/partials/header.html
=> release update latest version in header

Makefile, content/docs/release/changelog.md, content/docs/tutorial/get-started.md, content/docs/tutorial/vald-agent-standalone-on-k8s.md, content/docs/v1.2/release/changelog.md, content/docs/v1.2/tutorial/get-started.md, content/docs/v1.2/tutorial/vald-agent-standalone-on-k8s.md, themes/vald/layouts/partials/header.html
=> release v1.2.3

Makefile, content/docs/contributing/contributing-guide.md, content/docs/overview/component/index.md, content/docs/release/changelog.md, content/docs/tutorial/vald-agent-standalone-on-docker.md, content/docs/v1.2/contributing/contributing-guide.md, content/docs/v1.2/overview/component/index.md, content/docs/v1.2/release/changelog.md, content/docs/v1.2/tutorial/vald-agent-standalone-on-docker.md, themes/vald/layouts/partials/header.html
=> release v1.2.4

content/docs/overview/about-vald.md, content/docs/user-guides/configuration.md, content/docs/v1.3/overview/about-vald.md, content/docs/v1.3/user-guides/configuration.md
=> release remove deprecated sentences

themes/vald/layouts/_default/index.html
=> release update LP sentence

Makefile, content/docs/release/changelog.md, content/docs/v1.4/release/changelog.md, themes/vald/layouts/partials/header.html
=> release v1.4.1

Makefile, content/docs/api/serach.md, content/docs/support/contacts.md, content/docs/user-guides/_index.md, content/docs/user-guides/configuration.md, content/docs/user-guides/operations.md, content/docs/user-guides/sdks.md, content/docs/v1.4/api/serach.md, content/docs/v1.4/overview/about-vald.md, content/docs/v1.4/overview/architecture.md, content/docs/v1.4/user-guides/configuration.md, content/docs/v1.4/user-guides/operations.md
=> update API docs

Makefile, content/docs/tutorial/get-started.md
=> release remove invalid link

Makefile, content/docs/api/build_proto.md, content/docs/support/contacts.md, content/docs/support/faq.md, content/docs/tutorial/get-started.md, content/docs/tutorial/vald-agent-standalone-on-docker.md, content/docs/tutorial/vald-agent-standalone-on-k8s.md, content/docs/user-guides/troubleshooting.md, content/docs/v1.0/contributing/coding-style.md, content/docs/v1.0/contributing/contributing-guide.md, content/docs/v1.0/contributing/unit-test-guideline.md, content/docs/v1.5/api/build_proto.md, content/docs/v1.5/support/contacts.md, content/docs/v1.5/support/faq.md, content/docs/v1.5/tutorial/get-started.md, content/docs/v1.5/tutorial/vald-agent-standalone-on-docker.md, content/docs/v1.5/tutorial/vald-agent-standalone-on-k8s.md, content/docs/v1.5/user-guides/troubleshooting.md, themes/vald/layouts/partials/header.html
This PR should be merged after release v1.5.2.
I'll update `changelog` in another PR.
=> release add new docs and fix format

Makefile, content/docs/release/changelog.md, content/docs/v1.5/api/_index.md, content/docs/v1.5/release/changelog.md, init.sh
=> release changelog v1.5.2

themes/vald/layouts/_default/baseof.html
=> release fix index configuration

themes/vald/static/css/main.css
=> Adding dark-mode color for code sections

Makefile, content/docs/overview/component/filter-gateway.md, content/docs/release/changelog.md, content/docs/v1.5/overview/component/filter-gateway.md, content/docs/v1.5/release/changelog.md, themes/vald/layouts/partials/header.html
=> release v1.5.6

.github/workflows/auto-minify.yml, .github/workflows/release-prod.yml, Makefile, themes/vald/theme.toml
=> fix for main branch

content/docs/user-guides/backup-configuration.md, content/docs/user-guides/upgrade-cluster.md, content/docs/v1.5/user-guides/backup-configuration.md, content/docs/v1.5/user-guides/upgrade-cluster.md
=> release new document (upgrade cluster/backup config)

content/docs/api/build_proto.md, content/docs/api/filter-gateway.md, content/docs/performance/benchmark.md, content/docs/troubleshooting/client-side.md, content/docs/user-guides/configuration.md, content/docs/user-guides/filtering-configuration.md, content/docs/v1.6/api/build_proto.md, content/docs/v1.6/api/filter-gateway.md, content/docs/v1.6/api/status.md, content/docs/v1.6/performance/benchmark.md, content/docs/v1.6/troubleshooting/client-side.md, content/docs/v1.6/user-guides/configuration.md, content/docs/v1.6/user-guides/filtering-configuration.md
- Add new document
- Fix dead links
=>  Release new document

Makefile, content/docs/api/filter-gateway.md, content/docs/api/insert.md, content/docs/api/object.md, content/docs/api/remove.md, content/docs/api/search.md, content/docs/api/status.md, content/docs/api/update.md, content/docs/api/upsert.md, content/docs/release/changelog.md, content/docs/v1.7/api/filter-gateway.md, content/docs/v1.7/api/insert.md, content/docs/v1.7/api/object.md, content/docs/v1.7/api/remove.md, content/docs/v1.7/api/search.md, content/docs/v1.7/api/status.md, content/docs/v1.7/api/update.md, content/docs/v1.7/api/upsert.md, content/docs/v1.7/release/changelog.md, themes/vald/layouts/partials/header.html
=> release v1.7.1

Makefile, content/docs/release/changelog.md, content/docs/v1.7/release/changelog.md, themes/vald/layouts/partials/header.html
=> release v1.7.2

Makefile, content/docs/api/filter-gateway.md, content/docs/api/update.md, content/docs/api/upsert.md, content/docs/release/changelog.md, content/docs/user-guides/observability-configuration.md, content/docs/v1.7/api/filter-gateway.md, content/docs/v1.7/api/update.md, content/docs/v1.7/api/upsert.md, content/docs/v1.7/release/changelog.md, content/docs/v1.7/user-guides/observability-configuration.md, themes/vald/layouts/partials/header.html
=> release v1.7.3

content/docs/api/filter-gateway.md, content/docs/api/update.md, content/docs/api/upsert.md, content/docs/release/changelog.md, content/docs/v1.7/api/filter-gateway.md, content/docs/v1.7/api/update.md, content/docs/v1.7/api/upsert.md, content/docs/v1.7/release/changelog.md
=> release v1.7.3 (Fix typo)

config/production/config.toml, themes/vald/layouts/partials/googleanalytics.html
=> release adopt GA4

Makefile, content/docs/contributing/contributing-guide.md, content/docs/contributing/development.md, content/docs/v1.7/contributing/contributing-guide.md
=> release Fix invalid link path

.github/workflows/release-prod.yml, Makefile
=> Fix not showing version at the commit msg

Makefile, content/docs/user-guides/backup-configuration.md, content/docs/user-guides/network-policy.md, content/docs/user-guides/observability-configuration.md, content/docs/user-guides/sdks.md, content/docs/v1.7/user-guides/backup-configuration.md, content/docs/v1.7/user-guides/network-policy.md, content/docs/v1.7/user-guides/observability-configuration.md, content/docs/v1.7/user-guides/sdks.md
=> release adding new docs

Makefile, content/docs/release/changelog.md, content/docs/v1.7/release/changelog.md, themes/vald/layouts/partials/header.html
=> release v1.7.8

Makefile, content/docs/api/remove.md, content/docs/release/changelog.md, content/docs/tutorial/get-started.md, content/docs/tutorial/vald-agent-standalone-on-k8s.md, content/docs/user-guides/index-correction.md, content/docs/user-guides/sdks.md, content/docs/v1.7/api/remove.md, content/docs/v1.7/release/changelog.md, content/docs/v1.7/tutorial/get-started.md, content/docs/v1.7/tutorial/vald-agent-standalone-on-k8s.md, content/docs/v1.7/user-guides/index-correction.md, content/docs/v1.7/user-guides/sdks.md, themes/vald/layouts/partials/header.html
=> :arrow_up: release v1.7.9

Makefile, content/docs/release/changelog.md, content/docs/tutorial/get-started.md, content/docs/user-guides/deployment.md, content/docs/v1.7/release/changelog.md, content/docs/v1.7/tutorial/get-started.md, content/docs/v1.7/user-guides/deployment.md, themes/vald/layouts/partials/header.html
=> release v1.7.10

.github/workflows/release-prod.yml, themes/vald/layouts/partials/style.html
=> Release Fix CI and Add mermaid script

.github/workflows/auto-update-content.yml, themes/vald/layouts/_default/_markup/render-codeblock-mermaid.html, themes/vald/layouts/_default/single.html, themes/vald/layouts/partials/style.html
SSIA
ref: https://gohugo.io/content-management/diagrams/
=> Release: Add template for mermaid

Makefile
=> Fix Make init

.github/workflows/auto-update-content.yml, Makefile, go.mod
=> Fix update content bug

.github/workflows/auto-update-content.yml
=> Fix workflow typo

.github/workflows/auto-update-content.yml
=> Fix create pr wf

.github/workflows/auto-update-content.yml
=> Fix update content workflow

.github/workflows/chatops.yaml, magefile/magefile.go
=> Add UnPublish workflow

Makefile, content/docs/overview/component/agent.md, content/docs/v1.4/overview/component/agent.md, content/docs/v1.5/overview/component/agent.md, content/docs/v1.6/overview/component/agent.md, content/docs/v1.7/overview/component/agent.md, magefile/magefile.go
=> fix godoc version

themes/vald/layouts/partials/footer.html, themes/vald/layouts/partials/googleanalytics.html, themes/vald/layouts/partials/style.html
=> rewrite template with new hugo cmd instead of  deprecated cmd

.github/workflows/auto-minify.yml, .github/workflows/release-prod.yml, .gitmodules, Makefile
=> Change submodule path

.github/workflows/auto-update-content.yml
=> auto update content for each minor versions
